### ISSUE TITLE
API Key and Secret

### ISSUE THREAD

**Issue by chrisegge** [IgnitionModuleDevelopmentCommunity/IgnitionNode-RED#1]
Where do i find the API Key and Secret??
I have installed the Module and restarted ignition but I cannot find it.

**Comment by iatraviscox** [comment]
Once the module is installed, you have to login to the Ignition Gateway configuration page and select the Node-RED section from the left. There you can add an API key and secret. 

Regards, 

Travis Cox 
Co-Director of Sales Engineering 
Inductive Automation 
800.266.7798 [ callto:800.266.7798 ] | ext. 229 
[ mailto:travis@inductiveautomation.com | travis@inductiveautomation.com ] 

[ https://icc.inductiveautomation.com/ ]

**Comment by gabrielfpvh** [comment]
I am finding the same issue, but here is a bit more information about my case:

My machine is running an Edge Ignition software and I installed the 'Ignition-Node-RED-Module-signed.modl' module. Once installed, I cannot find any Node-RED section on the left. However, in the modules section I can see that the module is **Quarantined**:

Quarantine Reason: "**This module will not run on edge without a license.**"

Whats is the issue? How doe I/we solve the problem?

Thanks in advance for any support.

**Comment by gabrielfpvh** [comment]
Once added a license in the module.xml within the .modl file, the rising comment is:

Quarantine Reason: "**This module is unsigned and developer mode is disabled. This module will not run on edge without a license.**"

**Comment by iatraviscox** [comment]
Unfortunately, you need Ignition 7.9.9 to load that module. You also need to get the signed module from the GitHub page. Try that out and let me know if you have any problems. 

Regards, 

Travis Cox 
Co-Director of Sales Engineering 
Inductive Automation 
800.266.7798 [ callto:800.266.7798 ] | ext. 229 
[ mailto:travis@inductiveautomation.com | travis@inductiveautomation.com ] 

[ https://icc.inductiveautomation.com/ ]

**Comment by GarrickR** [comment]
I just installed on 7.9.9 Ignition Edge, and still getting the quarantined will not run without a license issue.  I have the signed module.  I have had no issue installing on Ignition Edge 7.9.4.  The 7.9.9 device is our EPIC-PR1, and the 7.9.4 is our GROOV-AR1 for reference.

**Comment by iatraviscox** [comment]
Hi Garrick, 

Yes sorry about that. We were supposed to fix that in 7.9.9 but that got moved to 7.9.10 which should be in beta within a week. Somehow we missed that. 

Regards, 

Travis Cox 
Co-Director of Sales Engineering 
Inductive Automation 
800.266.7798 [ callto:800.266.7798 ] | ext. 229 
[ mailto:travis@inductiveautomation.com | travis@inductiveautomation.com ] 

[ https://icc.inductiveautomation.com/ ]

**Comment by chrisegge** [comment]
I'm going to close this issue, my original problem has been resolved. Thank you
