### ISSUE TITLE
API in Ignition

### ISSUE THREAD

**Issue by LucSieben** [IgnitionModuleDevelopmentCommunity/IgnitionNode-RED#12]
Hi,

Sorry for another question, i am a real beginner in Ignition en Node Red.
But in Node Red i made a http request with an API in it that works in Node Red.
I search for a way to connect this in Ignition, but i got no luck.
Is there a way to connect this API/Node in Ignition?

Thanks for helping,

Luc

**Comment by LucSieben** [comment]
And another dumb question from me,
I installed the Node Red module in Ignition and made an API in the module. 
for the Ignition tag in Node Red i need a Tag Path where can I find this one?

**Comment by iatraviscox** [comment]
Correct. First you have to install the module into Ignition. Once you do that you need to set up an access token for the API that you use in NodeRED. In NodeRED you need to install the Ignition nodes which provides read and write nodes. The tag path can point to any tag in Ignition. A tag path looks like this:

`[default]path/to/my/tag`

The path above is a fully qualified path that includes the tag provider. You can set the default tag provider to "default" or whatever which allows you to leave that part out. I tend to use full paths.

You can find these tags by right clicking on a tag in the Ignition Designer and copying the path.

**Comment by LucSieben** [comment]
thanks for the reply it works now! 
thank you.
