### ISSUE TITLE
Event based triggers

### ISSUE THREAD

**Issue by mdeluca1992** [IgnitionModuleDevelopmentCommunity/IgnitionNode-RED#13]
Would love to have the ability to trigger a flow based on an event or tag change in Ignition without having to read the tag continuously. 

Current method - read tags from Ignition into Node Red then do something 

New idea - trigger a flow based on a tag change then do something

**Comment by iatraviscox** [comment]
I love that idea. The integration we have right now was very simple to prove it out. There is so much more we can do. Let me see what I can do with that. I will keep you posted. 

In the meantime, there is an OPC-UA client node that you can use:

[https://flows.nodered.org/node/node-red-contrib-opcua](https://flows.nodered.org/node/node-red-contrib-opcua)

With that you can subscribe to tags created in Ignition. You just need to expose our tag providers. You can find more information about that here:

[https://docs.inductiveautomation.com/display/DOC81/OPC+UA+Server+Settings](https://docs.inductiveautomation.com/display/DOC81/OPC+UA+Server+Settings)

**Comment by iatraviscox** [comment]
We have released a new version, 1.5.8, that includes a tag read node over web sockets so Ignition will push value changes into the flow versus polling for the values.

See [here](https://github.com/IgnitionModuleDevelopmentCommunity/IgnitionNode-RED/releases/tag/1.5.8).
