### ISSUE TITLE
node-red-contrib-ignition-nodes on Opto22 RIO

### ISSUE THREAD

**Issue by ryanjmclaughlin** [IgnitionModuleDevelopmentCommunity/IgnitionNode-RED#14]
Tried to install node-red-contrib-ignition-nodes on Opto22 RIO and get `Error: Cannot find module 'ws' (line:16)` 

Is there a way to install the dependency in a RIO?

**Comment by iatraviscox** [comment]
I assume various dependencies are already there like the ws package. It seems it is not there by default on that version of NodeRED on the RIO. If you can SSH into the RIO box you can definitely install them with:

`npm install ws`

I think I need to force the dependency in my package.json. I will get that done shortly.

**Comment by iatraviscox** [comment]
I uploaded a new version this morning that takes care of the dependencies.
