### ISSUE TITLE
New Node Red Install

### ISSUE THREAD

**Issue by tbackus** [IgnitionModuleDevelopmentCommunity/IgnitionNode-RED#15]
New Node Red Install using this newly updated 1.5.8 version and getting this error:
Flows stopped due to missing node types.

ignition-server
ignition-tag-write

Looking at Manage Pallet at installed nodes:
node-red-contrib-ignition-nodes
1.5.8
MODULE_NOT_FOUND

ignition-tag-read
ignition-tag-write
ignition-tag-read-ws
ignition-tag-browse
ignition-server

ignition-server is the only one that is not checked.  I have installed the Module in Ignition (it's being used with a different node red install) and verified the API string and key (again with the other node red install)..  

The older working node red install is version 1.5.7

**Comment by iatraviscox** [comment]
What version of NodeRED do you have?

**Comment by tbackus** [comment]
2.0.5

**Comment by iatraviscox** [comment]
Can you look at the NodeRED console logs to see what the error is? I tried on an older version that didn't have the ws javascript library and saw this error:

`[node-red-contrib-ignition-nodes/ignition-nodes] Error: Cannot find module 'ws'`

Do you have the same thing?

**Comment by tbackus** [comment]
I set console logging level to Debug and still just get the following...

- /usr/lib/node_modules/node-red/node_modules/@node-red/registry/lib/loader.js
- /usr/lib/node_modules/node-red/node_modules/@node-red/registry/lib/index.js
- /usr/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/nodes/index.js
- /usr/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/index.js
- /usr/lib/node_modules/node-red/lib/red.js
- /usr/lib/node_modules/node-red/red.js
19 Aug 14:26:45 - [info] Stopping flows
19 Aug 14:26:45 - [info] Stopped flows
19 Aug 14:26:45 - [info] Waiting for missing types to be registered:
19 Aug 14:26:45 - [info]  - ignition-tag-write
19 Aug 14:28:17 - [info] Stopping flows
19 Aug 14:28:17 - [info] Stopped flows
19 Aug 14:28:17 - [info] Waiting for missing types to be registered:
19 Aug 14:28:17 - [info]  - ignition-server
19 Aug 14:28:17 - [info]  - ignition-tag-write
19 Aug 14:29:30 - [info] Stopping flows
19 Aug 14:29:30 - [info] Stopped flows
19 Aug 14:29:30 - [info] Waiting for missing types to be registered:
19 Aug 14:29:30 - [info]  - ignition-server
19 Aug 14:29:30 - [info]  - ignition-tag-write
19 Aug 14:33:38 - [info] Stopping flows
19 Aug 14:33:38 - [info] Stopped flows
19 Aug 14:33:38 - [info] Waiting for missing types to be registered:
19 Aug 14:33:38 - [info]  - ignition-server
19 Aug 14:33:38 - [info]  - ignition-tag-write
19 Aug 19:42:18 - [info] Stopping flows

Also one other thing I just noticed, when I go in to put the API Token and Secret, those fields are empty and box outline is red.  Using the same key that I am using on the older version with no issues (cut and paste).  Even though I put the appropriate things in the fields, and save it and Deploy, I get the same errors "Flows stopped due to missing node types"

**Comment by iatraviscox** [comment]
I think it has to do with the same error I mentioned. Basically, I assume various dependencies are already there like the ws package. It seems it is not there by default. If you can SSH into the NodeRED server you can definitely install them with:

`npm install ws`

I think I need to force the dependency in my package.json. I will get that done shortly.

**Comment by tbackus** [comment]
That did it. Thanks. I did get a few more dependency errors trying to install ws, but it did install and I started node red again and it works great.

**Comment by tbackus** [comment]
Something else has cropped up now...
"Incorrect format for JSON POST data: {"defaultTagProvider":"default","apiToken":"xx","values":["1755"],"tagPaths":["[default]ANA_Test/reTerminal01/Cycle TimeMS"],"secret":"xx","command":"tagWrite"}"

The value is time in ms going into an Integer tag in Ignition....

**Comment by iatraviscox** [comment]
I uploaded a new version this morning that takes care of the dependencies. For the error, you need version 1.5.8+ for the NodeRED module in Ignition.
