### ISSUE TITLE
Tag read/write Incorrect format for JSON POST data

### ISSUE THREAD

**Issue by wpmccormick** [IgnitionModuleDevelopmentCommunity/IgnitionNode-RED#16]
I'm getting an _Incorrect format for JSON POST data_ error when doing tag read and writes on the latest version.

As soon as I updated _node-red-contrib-ignition-nodes_ to 1.5.9, I started getting the error.

I confirmed that it works in 1.5.7, and stopped working in both 1.5.8 and 1.5.9.

Additionally, there is a possible security issue in the log message (both sides) where the password is clear text.

**Comment by iatraviscox** [comment]
What version do you have for node-red-contrib-ignition-nodes and Ignition NodeRED module? They should match. You probably need to download the latest Ignition Module:

[https://github.com/IgnitionModuleDevelopmentCommunity/IgnitionNode-RED/releases/tag/1.5.9](https://github.com/IgnitionModuleDevelopmentCommunity/IgnitionNode-RED/releases/tag/1.5.9)

**Comment by wpmccormick** [comment]
Yep. That's what I missed. I suppose there's a note somewhere that both sides need to be updated.
