### ISSUE TITLE
Ignition Module faults

### ISSUE THREAD

**Issue by shaqaruden** [IgnitionModuleDevelopmentCommunity/IgnitionNode-RED#18]
After installing the ignition module, it faults saying `Not eligible for use with Ignition Edge, unless licensed`

Ignition: 8.1.11
Device: groov Rio MM2

**Comment by iatraviscox** [comment]
Yes, we need to add it to your license. Can you provide me the license key via email? (travis@inductiveautomation.com)

**Comment by shaqaruden** [comment]
I have a contact at Opto22 and they fixed the license for me. Thanks you your quick reply.
