### ISSUE TITLE
Should this work on 8.1.15??

### ISSUE THREAD

**Issue by tbackus** [IgnitionModuleDevelopmentCommunity/IgnitionNode-RED#21]
For some reason my gateway is showing this module in Trial mode., and when I try and write a tag, under quality I am getting name: "Bad_AccessDenied".  Have re done the API token about 4 times now with no change.

**Comment by iatraviscox** [comment]
Are you running on Ignition Edge or standard Ignition?

**Comment by tbackus** [comment]
Standard.

**Comment by iatraviscox** [comment]
The module ignores the license state so it will stay in trial mode but be fully active. Are you getting any logs in the Ignition status page?

**Comment by tbackus** [comment]
The only log for the last hour and a half is a couple of hsqlDataStore errors, Error thrown while attempting to cleanup stale schema records... Nothing related to the tag access denied errors:
`3/22/2022, 4:38:59 PM[node: d9241d39475bcf65](http://10.254.0.11:1880/#)
pi/40 : msg.payload : Object
object
ignitionResult: object
tagPath: "[default]PCM/PI/pi10000000c429446c/Cycle TimeMS"
value: "11757"
quality: object
isGood: false
intValue: -2147483134
name: "Bad_AccessDenied"
errorMessage: ""
statusCode: 1`

**Comment by iatraviscox** [comment]
Ok, do you have tag permissions on that tag or the tag provider?

**Comment by tbackus** [comment]
Looks like this tag provider is a remote tag provider.  I think that's causing it, let me setup to point to the local realtime tag provider on the other server.

**Comment by tbackus** [comment]
Yep that was the problem. Our tags are setup backwards, this server should be the Realtime tag provider and the other one should be the remote provider. Sorry for clogging up the works, but thanks for the quick replies as always!!

**Comment by iatraviscox** [comment]
No problem.
