### ISSUE TITLE
Invalid license in Ignition Edge 

### ISSUE THREAD

**Issue by rj187** [IgnitionModuleDevelopmentCommunity/IgnitionNode-RED#22]
Hi
I have installed the ignition node-red  module in ignition edge but after the installation it showing status as Faulted (Not eligible for use with Ignition Edge, unless licensed) and License is invalid 
is there anything i am missing here while installing 
ignition edge version i am using  is 8.1.16
can anybody help me with this ?

**Comment by cguillory7280** [comment]
If you have a valid license (not a trial) ask your technical account representative to add Node-RED to your license. I believe that being a third party module from Travis and Wes that it is not included in a standard Edge license but could be wrong about that.

CLINT GUILLORY
Automation Project Specialist
P 337-280-8368<tel:337-280-8368>

From: rj187 ***@***.***>
Sent: Thursday, April 21, 2022 7:26 AM
To: IgnitionModuleDevelopmentCommunity/IgnitionNode-RED ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [IgnitionModuleDevelopmentCommunity/IgnitionNode-RED] Invalid license in Ignition Edge (Issue #22)


Hi
I have installed the ignition node-red module in ignition edge but after the installation it showing status as Faulted (Not eligible for use with Ignition Edge, unless licensed) and License is invalid
is there anything i am missing here while installing
ignition edge version i am using is 8.1.16
can anybody help me with this ?

**Comment by cguillory7280** [comment]
Is it a trial given to you by an Ignition Representative or are you just using the two hour resettable trial, if the latter I don’t think it will run Node -Red in the standard two hour trial mode. If you are testing, talk to an Ignition Representative to find out if they would be willing to give you a limited time trial license for testing / development purposes.

CLINT GUILLORY
Automation Project Specialist
P 337-280-8368<tel:337-280-8368>

**Comment by iatraviscox** [comment]
Can you send to me (via email) your trial license key?

**Comment by rj187** [comment]
HI 
I am using the two-hour resettable trial, so I don't have a license key, as @cguillory7280  mentioned I guess I need a license to make it work, Or is there any way? 
Thanks & Regrades

**Comment by iatraviscox** [comment]
Unfortunately, the module will be only allowed to run on Edge (since it is 3rd party) when the Gateway is licensed. We can provide a trial license. You can either email me directly or contact your account representative.
