### ISSUE TITLE
Establishing a connection between node-red and Ignition edge   

### ISSUE THREAD

**Issue by Grs0918** [IgnitionModuleDevelopmentCommunity/IgnitionNode-RED#23]
Hi 
I have Installed ignition Node-RED module in the  ignition edge it's activated and running , in node-red Configuration page I want know Do I have create an API token And add that token in the node-red or I will get the token from someplace else 
If I have to create an API token Can any guide on how to do this ?
Thank you & Regards

**Comment by iatraviscox** [comment]
Yes, you have to create an API token in Ignition's configuration section under Node-RED -> API Tokens section. Once you do that you can set up the read or write nodes in Node-RED. Check the documentation in Node-RED for more details.

**Comment by Grs0918** [comment]
Hi 
I got it Working Thanks
