### ISSUE TITLE
ignition edge lags when using the ignition Node-RED module

### ISSUE THREAD

**Issue by Grs0918** [IgnitionModuleDevelopmentCommunity/IgnitionNode-RED#25]
Hi when I am using ignition Node-RED module , earlier I was able to read all the tags from gateway but when the number of tags in ignition edge is increased the gateway take forever to load and I am unable to read any tags since I am getting connection timeout or Socket hang up error but when I remove ignition Node-red modl the gateway works fine 
can anybody help me with this

**Comment by iatraviscox** [comment]
Can you provide a few more details? Which nodes are you using exactly? How many tags are you trying to read?

**Comment by Grs0918** [comment]
Hi
I am using node-red -contrib- ignition-nodes version 1.5.9 and using the
ignition tag read node to read the data from the gateway  and I am trying
to read around 25,000 tags and more in the future
ignition version - ignition-edge 8.1.16 Linux  let me know any other
details you need
Thank you

**Comment by iatraviscox** [comment]
The read node sends down a set of tags that Ignition will read. It will definitely be more efficient to read in bulk vs individual. There is not a limit but the more you send the more work Ignition has to do. However, the web socket node simply subscribes (like an Ignition client) and receives updates when values change. Much different approach.

**Comment by Grs0918** [comment]
Hi
So I have tried ws tag read node it seems to be working without hanging up
edge gateway,
Also does the API token created in edge for node-red expires over a
period of time?
