### ISSUE TITLE
Unable to Write to the Ignition Tag's

### ISSUE THREAD

**Issue by Grs0918** [IgnitionModuleDevelopmentCommunity/IgnitionNode-RED#26]
Hi 
I am Trying to write to ignition tags using tag write node , 
The Tag Value and the TagPath are in format of msg.payload & msg.payload.lcc written in function node 
`````````````````
var newMsg =    { 
                    payload:    {
                                    tagValue:msg.payload,
                                    tagProvider:'edge',
                                    tagPath:[msg.payload.lcc,
                                    
                                    ]
                                } 
                };
return newMsg;

`````````````````
I am not able to write to tag using this function can anyone tell me the right way to do this .

**Comment by iatraviscox** [comment]
The payload just needs tagPath and tagValue:

`{
    "tagPath": "[default]mytag",
    "tagValue": 20
}`

**Comment by Grs0918** [comment]
Hi 
Just tried it it but it is not writing the value to the tag attached screenshot below 
![image](https://user-images.githubusercontent.com/105702817/189175860-c2af0241-986f-4b3a-8dde-e072af78df4b.png)
In debug window the output of the tag Write node in debug 6 Value is empty 
Is there something I am doing it wrong?

**Comment by Grs0918** [comment]
No it is just single value in msg.payload : Object format

**Comment by iatraviscox** [comment]
Can you show me the debug output after the function node?

**Comment by Grs0918** [comment]
![image](https://user-images.githubusercontent.com/105702817/189189555-b266aac1-5ceb-4a3c-860e-7ebedc2f2afa.png)
Yeah The Values are not injecting at once, realized the issue .
Thanks for the help !
