### ISSUE TITLE
ignition tag read ws - no able to save heartbeat parameter

### ISSUE THREAD

**Issue by pirboucher** [IgnitionModuleDevelopmentCommunity/IgnitionNode-RED#28]
When using the node “ignition tag read ws” from the Node-Red library “node-red-contrib-ignition-nodes”, the Node-Red editor does not save the heartbeat parameter.

![2022-09-14_10-03-48](https://user-images.githubusercontent.com/6692926/190243821-7e2305b7-0227-4df3-8d26-4751939d45cb.png)

Without the heartbeat, the Ignition Gateway logs are filled with warnings which repeat every 5 minutes (300000 ms). This delay corresponds to the default timeout value for web socket in Node.js.

![2022-09-13_15-49-08](https://user-images.githubusercontent.com/6692926/190243871-9f9b4516-9df9-47a3-b509-fd07ece10ba9.png)

The impact on my application is that every 5 minutes, the node disconnects itself from the Ignition server and could result in a lost of data. The workaround I found to fix this issue is to export the node and manually edit the heartbeat parameter value directly in the json file (i.e. “hb” = 1), then reimporting the file in Node-Red.

It would be nice to fix this issue.

**Comment by iatraviscox** [comment]
Thanks for reporting the issue. I have fixed this in 1.5.11:

[https://github.com/IgnitionModuleDevelopmentCommunity/IgnitionNode-RED/releases/tag/1.5.11](https://github.com/IgnitionModuleDevelopmentCommunity/IgnitionNode-RED/releases/tag/1.5.11)
