### ISSUE TITLE
Not eligible for use with Ignition Edge, unless licensed

### ISSUE THREAD

**Issue by knussbaumer1** [IgnitionModuleDevelopmentCommunity/IgnitionNode-RED#29]
When attempting to install on a licensed Ignition Edge system, the module goes to Faulted state with the message "Not eligible for use with Ignition Edge, unless licensed". It is unclear what license is required for this to function.

I also see a ModuleManager log entry that says "Module "org.imdc.nodered.IgnitionNodeRED" license state is invalid, aborting setup."

**Comment by iatraviscox** [comment]
You can't add it to Edge without the the module whitelisted in the license. Can you email or private message me your license key so I can add it?

**Comment by iatraviscox** [comment]
Fixed by adding the module to the Edge license.
