### ISSUE TITLE
How fetch all the Tags value present in Tag Browser in One Instances 

### ISSUE THREAD

**Issue by Grs0918** [IgnitionModuleDevelopmentCommunity/IgnitionNode-RED#30]
Hi 
1) I want Read All the Tags that are present in the Tag Browser at Once, I am Giving Just the Provider path in tagPath like [edge] and I want to read all the Data present in that provider, Currently, I am unable to read it.
Need help to achieve this
2) Also What is the Max number of Connections or Nodes I can use Before it Starts Giving me an HTTP: Scoket hang-up error?

Thanks

**Comment by iatraviscox** [comment]
You can read all of the tags at once using the web socket read node. You can specify a wildcard path, like this:

`[edge]*`

That would subscribe to all of the tags in the default provider. Regarding the second question, I don't have the answer. It would be related to Ignition's Gateway performance but I have not done the benchmarks.

**Comment by Grs0918** [comment]
Hi 
I tried using [edge]* it gave me all tags values which is what I wanted, is there any way that I can get all these values in a Single JSON File  Currently it is Sending all the values individually 
After Receiving the values I am sending them through API to another Application

**Comment by iatraviscox** [comment]
Not currently since there would be some performance implications. You can use the read tag node but you would have to specify all of the tag paths.

**Comment by iatraviscox** [comment]
Closing
